baseurl: /
url: "http://codingdavinci.de"
registerurl: /anmeldung/
markdown: kramdown

sass:
  style: compressed

permalink: /news/:year/:month/:day/:title.html

plugins_dir: [jekyll-paginate]
# plugins: [jekyll-paginate]
gems: [jekyll-paginate]

collections:
  projects :
    output: true


paginate: 7
paginate_path: "/news/page:num/"
